clone:
  git:
    image: plugins/git:next
    pull: true

pipeline:
  test:
    image: alpine
    commands:
      - echo 'fifth branch needs stuff in the beginning'
      - echo 'success'
      - echo 'that must really be here'
      - echo 'again'
